### ISSUE TITLE
WarioWare D.I.Y. DS saves but with the Wii's and DLC content

### ISSUE THREAD

**Issue by ghost** [Universal-Team/Universal-Updater#133]
[WarioWare D.I.Y. clean no cheats fresh micros saves - quick port from the GameFaqs D.I.Y. Showcase saves (Rev 1).zip](https://github.com/Universal-Team/Universal-Updater/files/9568521/WarioWare.D.I.Y.clean.no.cheats.fresh.micros.saves.-.quick.port.from.the.GameFaqs.D.I.Y.Showcase.saves.Rev.1.zip)

if there's some DS homebrew stuff like S8DS/jEnesisDS for example could it be possible to add these saves to this Universal Updater too, just wondering, i'm not trying to force you guys to add them to this app.

they get installed straight to the TwilightMenu++ NDS saves folder obviously.

**Comment by NightScript370** [comment]
This is irrelevant for Universal-Updater, but should be in Universal-DB. Although, we would probably end up rejecting it there too, because of it not being an application on its own, but instead being tied to something that nintendo published.

In addition, not everyone uses the /roms/nds/ structure, making this much more cumbersome to setup properly. Sorry.

**Comment by NightScript370** [comment]
This will undoubtedly be spammed, so I'm locking it.
