### ISSUE TITLE
Cannot find Universal Updater scripts in /3ds/Universal-Updater/scripts in latest version

### ISSUE THREAD

**Issue by SirEnder125** [Universal-Team/Universal-Updater#63]
Hey. I recently downloaded the latest version of this homebrew and
I believe script support is gone. Why has this happened? How do I use
my custom scripts now?

**Comment by SuperSaiyajinStackZ** [comment]
That is right. Scripts have been removed with Version v3.0.0, because UniStores are the way to go now. Scripts were basically a weaker version of UniStores so it didn't make sense to keep Scripts support. Universal-Updater is now based as a Homebrew app store.

Also without Scripts, Universal-Updater is also more straight forward to use now, because only UniStores are usable now and with that.. the full app got overhauled. Rework your custom script to a UniStore, if you really want to use it again, see the wiki section for more.

I will close this now, as this is not an issue.
