### ISSUE TITLE
[Feature Request] Allow forgetting an installed app

### ISSUE THREAD

**Issue by SNBeast** [Universal-Team/Universal-Updater#83]
**Is your feature request related to a problem? Please describe.**
I am unable to tell the app that I want it to forget that I installed something in-app. My example was mikewii's Luma3DS-plugin: I replaced it (with Nanquitas'), but when mikewii updated I got the icon suggesting I update that software which I didn't have.

**Describe the solution you'd like**
My considered solution is that there's a button in either an app's info or download page that allows removing the app from the installation log.

**Describe alternatives you've considered**
There is manually editing the JSON, but that's too conducive to messing things up.

**Comment by SNBeast** [comment]
Whoops, forgot the title

**Comment by Epicpkmn11** [comment]
Oops forgot to do the fixes thing in the commit, fixed by 11238eea22dd4168b81663667906729b2ba7e1be. It won't apply retroactively since any app installed prior to v3.2.0 won't have anything marked as installed so I don't want to have it just clear all updated dates from apps that don't have an installed entry, but it should work pretty well going forward, just mark all of the entries as uninstalled (tap the SD card icon) and it'll automatically clear the update tracking too.
